# Dependencies
markdown:         kramdown
highlighter:      pygments

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:        pretty

# Setup
title:            John Pinkerton
tagline:          'A man'
description:      'Full Stack Web Developer'
url:              http://johnpinkerton.me

author:
  name:           'John Pinkerton'
  url:            https://twitter.com/johnthepink

feed:
  path: atom.xml

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/johnthepink/johnthepink.github.io
